# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'makingLunch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for makingLunch

  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Core'

  target 'makingLunch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'makingLunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

