# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'makingLunch' do

  rn_maps_path = '../node_modules/react-native-maps'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for makingLunch

  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Core'
  
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path 
  pod 'GoogleMaps'  
  pod 'Google-Maps-iOS-Utils'

  target 'makingLunch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

    pod 'react-native-config', :path => '../node_modules/react-native-config'

    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  end

  target 'makingLunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end