# this should be the folder name under `ios` for your project
project_name = 'makingLunch'

# NOTE: This is meant to be run on CI where it changes everything before building the app.
# Usage:
# `RN_RELEASE_TYPE=beta fastlane prep_release_type` (on CI these ENV variables should be set via the UI)

desc "Updates the app identifier, display name and icon for alpha, beta, and production releases"
lane :prep_release_type do
  # alpha, beta, production
  type = ENV['RN_RELEASE_TYPE']
  suffix = type
  
  # assumes identifier is defined in Appfile
  app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  new_app_id = "#{app_id}.#{suffix}"

  # update the app identifier and bundle
  UI.message "\n\nSetting app identifier to: #{new_app_id}"

  display_name = ENV['RN_DISPLAY_NAME'] || type.capitalize
  UI.message "\n\nSetting Display Name to: #{display_name}"

  # update ios indentifier
  #update_info_plist(
  #  plist_path: "#{project_name}/Info.plist",
  #  xcodeproj: "./ios/#{project_name}.xcodeproj",
  #  display_name: display_name,
  #  app_identifier: new_app_id
  #)

  # update android display name
    update_android_strings(
      block: lambda { |strings|
        strings['app_name'] = display_name
      }
)

  # update android suffix
  set_value_in_build(
    app_project_dir: "./android/app",
    key: "applicationIdSuffix",
    value: ".#{suffix}"
  )

# android badge
  add_badge(
    glob: "/android/app/src/main/res/**/ic_launcher.{png,PNG}", # note no dot in path
    no_badge: type == 'prod'
  )

end